### ISSUE TITLE
Ignorefile case sensitivity is broken

### ISSUE THREAD

**Issue by spaluchowski** [americanexpress/earlybird#10]
.ge_ignore file case sensitivity works in a weird way. At least on Windows machine. Entries in ignore file have to be put in lower case to match something.

The problem is that when in ignore file is entry: '\*.txt' it matches any \*.txt files (i.e. Readme.txt, readme.TXT) which is good behavior. 
But when I put entry "\*.TXT" it does not match anything (at least not expecting readme.TXT). 
It showed when I tried to exclude some path which contained word "Libs" (i.e. "Libs/sweet.lib"). When I tried with all combinations of "\*/Libs/\*", "\*Libs\*", "Libs\*" nothing worked. Only "\*/libs/\*" was matching.

This is not a huge problem, but it is a very counter intuitive behavior.  

Version: 1.24.6

**Comment by aschaef19** [comment]
We tested this on both Windows and Mac, but we were unable to reproduce the issue. 

We tested with lowercase `*.txt` and uppercase `*.TXT` file extensions in .ge_ignore, and in both cases, all .txt/.TXT files were ignored. 

We tested similarly with folder names, `*\libs\*` and `*\Libs\*`, and in both cases, all the files in the libs/Libs folder were ignored. 

The only discrepancy found was that on Windows, we had to provide the ignored paths using `\` instead of `/`. Please let us know if this is not the issue you were facing.

**Comment by grinish21** [comment]
Closing issue due to no response
